### ISSUE TITLE
error

### ISSUE THREAD

**Issue by huybopbii** [aarinstech/HBOMB#1]
Unexpected Error

**Comment by aarinstech** [comment]
Hi huybopbii,
 
Thank you for contacting aarinstech Support

 I apologize for the inconvenience

 I request you to please share a screenshot of the error that you're facing

Your patience is appreciated.


Regards,
aarinstech

My official social media handles are:- 
Instagram: aarinstech
Twitter: aarinstech
Telegram: aarinstech

You can also contact me via e-mail: aarinsingh33@gmail.com

**Comment by huybopbii** [comment]
oke
